### ISSUE TITLE
VGM is now officially on spack 

### ISSUE THREAD

**Issue by DraTeots** [vmc-project/vgm#3]
https://github.com/spack/spack/pull/17741

Would be nice if VGM developers would have a look from time to time that their package is actual on spack

**Comment by ihrivnac** [comment]
Dear @DraTeots ,

Thank you for adding VGM. As I am not involved in any project using spack, could you, please, let me know what is expected from me by this "would have a look from time to time that their package is actual on spack" ?

**Comment by wdconinc** [comment]
While @DraTeots is on leave, I'm happy to respond (I'm the author of the spack package and linked pr).

Spack is a package manager for HPC systems (as you may know). As one of the users of vgm using spack, I have this repo on my watch list so I should notice new releases and can enable them in the spack package (adding a version and sha hash, typically). Spack relies on community members (like me) to add new versions, since that is not a burden that should fall on developers unless they choose to.

What typically helps out, though, is if any changes in the dependencies (e.g. minimum versions) or build system are indicated in the release notes by developers. Thanks in advance!

**Comment by ihrivnac** [comment]
@wdconinc ,

Ok, thank you, I will keep that in mind in the future tags.
