### ISSUE TITLE
ScaledSolid tests failing

### ISSUE THREAD

**Issue by olifre** [vmc-project/vgm#5]
Hi,

for me, all the "test3" tests with ScaledSolids are segfaulting. 
I am using VGM 4.9, Geant-VMC4 5.3, Geant 4.10.7, VMC 1.0_p3, ROOT 6.22.06 and non-embedded clhep 2.4.4.0. 

I attach the output of:
```
./vgm_test VGM Geant4 None noXML ScaledSolids noVis run
```
here:
[err.log](https://github.com/vmc-project/vgm/files/5721264/err.log)

All ScaledSolid tests are failing on my end in this way. 

Checking with GDB, I see the first issue in `G4NormalNavigation::ComputeStep` which has these locals:
```
(gdb) info locals
motherPhysical = 0x5555567c5d20
samplePhysical = <optimized out>
blockedExitedVol = 0x0
motherLogical = <optimized out>
motherSolid = 0x5555567c5ae0
sampleDirection = {data = {0, 0, 0}, static tolerance = 2.22045e-14}
ourStep = <optimized out>
ourSafety = 8.5265128291212022e-14
motherSafety = 8.5265128291212022e-14
motherStep = 1.7976931348623157e+308
localNoDaughters = <optimized out>
sampleNo = <optimized out>
motherValidExitNormal = false
motherExitNormal = {data = {0, 0, 0}, static tolerance = 2.22045e-14}
```
So already here, the `motherExitNormal` is `0,0,0`. This seems to be passed down deeper into `G4ScaledSolid::DistanceToOut` which then evaluates `normal/normal.mag()` which CLhep does not like for this bad normal vector. 

Do you have an idea what is going wrong here, or how to continue debugging it?

**Comment by ihrivnac** [comment]
Hi @olifre ,

Thank you for reporting the problem. I was able to reproduce it; it escaped our testing as the break does not happen when using Geant4 internal CLHEP.
The problem is now being fixed in Geant4 development version and when the fix is finalized, it should be ported also to the patch to 10.7. 
Before the fix is provided, you can either switch to use Geant4 internal CLHEP, or switch off this test in the test suite.
I will keep the issue open until the fix in Geant4 is available.

Best regards,

**Comment by olifre** [comment]
Hi @ihrivnac ,

many thanks for the quick investigation and fixing this in Geant4! I'll disable the test in the test suite for now until the new version is out :smile: . 

All the best,
Oliver

**Comment by ihrivnac** [comment]
Hi @olifre ,
Should be ok with  Geant4 10.7.p01. Can you confirm?
Thank you,

**Comment by olifre** [comment]
Hi @ihrivnac ,

thanks for coming back to this, indeed, I ran all tests just now against Geant4 10.7.p01 and can confirm everything is "green" now :smile: . 

Many thanks!
